version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pretty_assertions
    versions:
    - 0.7.0
    - 0.7.1
  - dependency-name: typed-builder
    versions:
    - 0.8.0
    - 0.9.0
  - dependency-name: reqwest
    versions:
    - 0.11.0
  - dependency-name: tokio
    versions:
    - 0.2.24
  - dependency-name: serde_qs
    versions:
    - 0.8.1
